[server]
source="/go/src/app/"
backup="/go/src/app/bkup/{YYYY}/{MM}/{DD}/{WW}"

[file]
source="勤怠管理{YYYY}年({MM}月)({EMPNUM}_{EMPNAME}).xlsx"
backup="勤怠管理{YYYY}年({MM}月)({EMPNUM}_{EMPNAME})_{EMPAPARTMET}.xlsx"

[[templates]]
pattern="EMPNUM"
value="598"

[[templates]]
pattern="EMPNAME"
value="YOUR NAME"

[[templates]]
pattern="EMPAPARTMET"
value="DEVELOPMENT"